### ISSUE TITLE
Is a token required for public gists?

### ISSUE THREAD

**Issue by mindrones** [jvcalderon/gist-client#1]
Hi, related to https://github.com/sveltejs/svelte.technology/issues/382, I'm trying to retrieve public gists containing the word "svelte":

```js
const GistClient = require("gist-client");
const gistClient = new GistClient();

gistClient
.getAll({
    rawContent: true,
    filterBy: [
        {public: true},
        {content: "svelte"},
        {since: "2018-11-01T00:00:01Z"}
    ]
})
.then(gistList => {
    console.log(JSON.stringify(gistList))
})
.catch(err => {
    console.log(err)
});
```

but I get the error `Error: You need to set token before by setToken() method`.
According to https://github.com/jvcalderon/gist-client#get-a-gist-list it seemed that this should work without a token? Thanks!

**Comment by jvcalderon** [comment]
[This commit](https://github.com/jvcalderon/gist-client/commit/3f42394c28c593244f8bc9360c863e257575ab4f) solves the problem. It was an unnecessary token check. Now (v.1.0.8) you can use getAll method without token, to retrieve public gists. Thank you for your feedback @mindrones

**Comment by mindrones** [comment]
Cool, worked perfectly to retrieve my own gists with this (no token):

```js
.getAll({
    filterBy: [
        {userName: "mindrones"},
    ]
})
```

Thanks!

Note aside, this one:
```js
.getAll({
    rawContent: true,
    filterBy: [
        {userName: "mindrones"},
        {content: "svelte"},
    ]
})
```
fails with a 
```
TypeError: _.get(...).match is not a function
node_modules/gist-client/lib/gistClient.js:223:61
```

Not sure if that's supposed to work or wrong config. If needed can open a new issue.

**Comment by jvcalderon** [comment]
@mindrones I just published [v.1.0.9](https://www.npmjs.com/package/gist-client/v/1.0.9) it solves a bug when gists files contained JSON files. You can see the change in this [commit](https://github.com/jvcalderon/gist-client/commit/103404c225f85c2315a49cb9d127b28e1b01083c)

**Comment by mindrones** [comment]
Works! Thanks a lot for these quick fixes, closing :)
